language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

node_js:
  - "node"

before_install:
  - pip install -U tox tox-travis
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - .travis/run.sh

matrix:
  include:
  - language: ruby
    script: bundle exec rake
    rvm: 2.1
